# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [26]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [27]:
vacation_csv_file = "output_data/cities.csv"
vacation_df = pd.read_csv(vacation_csv_file)
vacation_df

,City,Country,Humidity,Longitude,latitude,Date,Max Temp,Wind Speed,cloudiness
0,Castro,BR,66,-50.0119,-24.7911,1661672619,57.58,3.06,70
1,Laguna,US,73,-121.4238,38.4210,1661672619,71.78,8.05,0
2,Cherskiy,RU,49,161.3000,68.7500,1661672620,60.64,11.16,94
3,Pevek,RU,87,170.3133,69.7008,1661672620,37.17,6.89,11
4,São João da Barra,BR,90,-41.0511,-21.6403,1661672621,69.64,14.83,2
...,...,...,...,...,...,...,...,...,...
574,Pucallpa,PE,84,-74.5539,-8.3791,1661672840,70.11,1.70,19
575,Port-Gentil,GA,78,8.7815,-0.7193,1661672841,76.96,10.36,75
576,Auki,SB,88,160.7034,-8.7676,1661672841,76.68,5.97,87
577,Coihueco,CL,87,-71.8333,-36.6167,1661672841,36.34,9.22,0
578,Wolgast,DE,81,13.7667,54.0500,1661672842,66.22,10.25,100

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [28]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

# Convert Humidity to float and store
# Also, handle NaN values
vacation_df = vacation_df.dropna()
humidity = vacation_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations. 
locations = vacation_df[["latitude", "Longitude"]].astype(float)

# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(vacation_df["Humidity"]),
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [29]:
# Narrow down the DataFrame for ideal weather condition
clean_vacation_df = vacation_df



# A max temperature lower than 80 degrees but higher than 70.
clean_vacation_df = clean_vacation_df.loc[(clean_vacation_df["Max Temp"] < 80) & (clean_vacation_df["Max Temp"] > 70)]

# Wind speed less than 10 mph.
clean_vacation_df = clean_vacation_df.loc[clean_vacation_df["Wind Speed"] < 10]

# Zero cloudiness.
clean_vacation_df = clean_vacation_df.loc[clean_vacation_df["cloudiness"] == 0]

# Drop any rows with null values
clean_vacation_df = clean_vacation_df.dropna(how="any")

clean_vacation_df

,City,Country,Humidity,Longitude,latitude,Date,Max Temp,Wind Speed,cloudiness
1,Laguna,US,73,-121.4238,38.4210,1661672619,71.78,8.05,0
100,Sète,FR,51,3.6966,43.4018,1661672394,77.88,2.64,0
172,Pascagoula,US,97,-88.5561,30.3658,1661672637,77.05,0.00,0
173,Khalkhāl,IR,18,48.5258,37.6189,1661672685,76.37,3.11,0
216,Marabá,BR,100,-49.1178,-5.3686,1661672689,71.78,0.00,0
223,Asău,RO,34,26.4000,46.4333,1661672704,74.32,1.23,0
247,Adelanto,US,53,-117.4092,34.5828,1661672714,73.69,8.68,0
257,Cayenne,GF,100,-52.3333,4.9333,1661672717,71.64,0.00,0
278,Wilmington,US,91,-77.9447,34.2257,1661672718,74.86,0.00,0
322,West Wendover,US,20,-114.0733,40.7391,1661672743,72.61,0.00,0
348,Cabot,US,96,-92.0165,34.9745,1661672752,78.10,0.00,0
406,Mayfield,US,90,-88.6367,36.7417,1661672776,74.14,3.44,0
414,Vulcan,RO,41,23.2667,45.3833,1661672779,78.75,1.61,0
415,Winnetka,US,80,-87.7359,42.1081,1661672779,73.24,6.91,0
443,Sterling,US,89,-77.4286,39.0062,1661672725,74.89,4.61,0
469,Fort Frances,CA,43,-93.4003,48.5999,1661672541,71.82,7.00,0
471,La Carolina,ES,51,-3.6153,38.2756,1661672801,78.08,2.37,0
495,Arrondissement d'Ajaccio,FR,65,8.9167,42.0000,1661672810,77.05,2.30,0
501,Hamilton,US,90,-84.5333,39.1834,1661672624,70.93,5.75,0
507,Ihosy,MG,35,46.1167,-22.4000,1661672814,74.17,5.97,0
508,Caţa,RO,37,25.2667,46.0833,1661672815,79.95,1.74,0
568,Madison,US,91,-86.5667,34.7334,1661672599,76.68,5.01,0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [30]:
hotel_df = clean_vacation_df

# define parameters 
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"obtaining data results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    #print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing data: skipped")
        
    print("------------")

obtaining data results for Index 1: Laguna.
Closest hotel is Holiday Inn Express & Suites Elk Grove Central - Hwy 99, an IHG Hotel.
------------
obtaining data results for Index 100: Sète.
Closest hotel is Hotel de Paris Sète.
------------
obtaining data results for Index 172: Pascagoula.
Closest hotel is Regency Inn.
------------
obtaining data results for Index 173: Khalkhāl.
Closest hotel is Khalkhal Tourist Hotel.
------------
obtaining data results for Index 216: Marabá.
Closest hotel is Hotel Del Principe.
------------
obtaining data results for Index 223: Asău.
Closest hotel is Casa Mika Ciobanus.
------------
obtaining data results for Index 247: Adelanto.
Closest hotel is Days Inn Adelanto-Victorville.
------------
obtaining data results for Index 257: Cayenne.
Closest hotel is Hôtel Le Dronmi.
------------
obtaining data results for Index 278: Wilmington.
Closest hotel is Hotel Ballast Wilmington, Tapestry Collection by Hilton.
------------
obtaining data results for Index 322: West Wendover.
Closest hotel is Motel 6 Wendover, UT.
------------
obtaining data results for Index 348: Cabot.
Closest hotel is Super 8 by Wyndham Cabot.
------------
obtaining data results for Index 406: Mayfield.
Closest hotel is Super 8 by Wyndham Mayfield.
------------
obtaining data results for Index 414: Vulcan.
Closest hotel is Green Paradise Restaurant.
------------
obtaining data results for Index 415: Winnetka.
Closest hotel is Chicago Motel.
------------
obtaining data results for Index 443: Sterling.
Closest hotel is Hampton Inn & Suites Washington-Dulles International Airport.
------------
obtaining data results for Index 469: Fort Frances.
Closest hotel is LA PLACE RENDEZ-VOUS.
------------
obtaining data results for Index 471: La Carolina.
Closest hotel is NH La Perdiz.
------------
obtaining data results for Index 495: Arrondissement d'Ajaccio.
Closest hotel is Sole E Monte.
------------
obtaining data results for Index 501: Hamilton.
Closest hotel is Six Acres Bed & Breakfast.
------------
obtaining data results for Index 507: Ihosy.
Closest hotel is Tamana hôtel.
------------
obtaining data results for Index 508: Caţa.
Missing data: skipped
------------
obtaining data results for Index 568: Madison.
Closest hotel is Embassy Suites by Hilton Huntsville.
------------

In [31]:
hotel_df

,City,Country,Humidity,Longitude,latitude,Date,Max Temp,Wind Speed,cloudiness,Hotel Name
1,Laguna,US,73,-121.4238,38.4210,1661672619,71.78,8.05,0,Holiday Inn Express & Suites Elk Grove Central...
100,Sète,FR,51,3.6966,43.4018,1661672394,77.88,2.64,0,Hotel de Paris Sète
172,Pascagoula,US,97,-88.5561,30.3658,1661672637,77.05,0.00,0,Regency Inn
173,Khalkhāl,IR,18,48.5258,37.6189,1661672685,76.37,3.11,0,Khalkhal Tourist Hotel
216,Marabá,BR,100,-49.1178,-5.3686,1661672689,71.78,0.00,0,Hotel Del Principe
223,Asău,RO,34,26.4000,46.4333,1661672704,74.32,1.23,0,Casa Mika Ciobanus
247,Adelanto,US,53,-117.4092,34.5828,1661672714,73.69,8.68,0,Days Inn Adelanto-Victorville
257,Cayenne,GF,100,-52.3333,4.9333,1661672717,71.64,0.00,0,Hôtel Le Dronmi
278,Wilmington,US,91,-77.9447,34.2257,1661672718,74.86,0.00,0,"Hotel Ballast Wilmington, Tapestry Collection ..."
322,West Wendover,US,20,-114.0733,40.7391,1661672743,72.61,0.00,0,"Motel 6 Wendover, UT"
348,Cabot,US,96,-92.0165,34.9745,1661672752,78.10,0.00,0,Super 8 by Wyndham Cabot
406,Mayfield,US,90,-88.6367,36.7417,1661672776,74.14,3.44,0,Super 8 by Wyndham Mayfield
414,Vulcan,RO,41,23.2667,45.3833,1661672779,78.75,1.61,0,Green Paradise Restaurant
415,Winnetka,US,80,-87.7359,42.1081,1661672779,73.24,6.91,0,Chicago Motel
443,Sterling,US,89,-77.4286,39.0062,1661672725,74.89,4.61,0,Hampton Inn & Suites Washington-Dulles Interna...
469,Fort Frances,CA,43,-93.4003,48.5999,1661672541,71.82,7.00,0,LA PLACE RENDEZ-VOUS
471,La Carolina,ES,51,-3.6153,38.2756,1661672801,78.08,2.37,0,NH La Perdiz
495,Arrondissement d'Ajaccio,FR,65,8.9167,42.0000,1661672810,77.05,2.30,0,Sole E Monte
501,Hamilton,US,90,-84.5333,39.1834,1661672624,70.93,5.75,0,Six Acres Bed & Breakfast
507,Ihosy,MG,35,46.1167,-22.4000,1661672814,74.17,5.97,0,Tamana hôtel
508,Caţa,RO,37,25.2667,46.0833,1661672815,79.95,1.74,0,NaN
568,Madison,US,91,-86.5667,34.7334,1661672599,76.68,5.01,0,Embassy Suites by Hilton Huntsville

In [46]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["latitude", "Longitude"]]

In [43]:
# Add marker layer ontop of heat map
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Add the layer to the map
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))